In [1]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
print( arr)
print( arr.ndim)
print( arr.shape)
print( arr.size)
print(arr.dtype)

[10 20 30 40 50]
1
(5,)
5
int64


In [2]:
arr2 = np.random.randint(0, 51, size=(4, 5))
print(arr2)
print( arr2.itemsize)
print( arr2.nbytes)
print(arr2[arr2 % 5 == 0])

[[27 16  5 20 42]
 [21 32 47 10 19]
 [42 45  0 14 18]
 [28 45 13 47 16]]
4
80
[ 5 20 10 45  0 45]


In [3]:
arr3 = np.arange(1, 13).reshape(3, 4)
print(arr3)
print( arr3.shape[0])
print( arr3.shape[1])
reversed_columns = arr3[:, ::-1]
print(reversed_columns)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
3
4
[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]


In [4]:
arr4 = np.arange(1, 13).reshape(3, 4)
print(arr4)
view = arr4[0:2, 0:2]
print(view)
view[0, 0] = 100
print(view)
print(arr4)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[1 2]
 [5 6]]
[[100   2]
 [  5   6]]
[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [5]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
print( arr)
print( arr.ndim)
print( arr.shape)
print( arr.size)
print(arr.dtype)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
1
(20,)
20
int64


In [6]:
import numpy as np
np.random.seed(0)
arr2 = np.random.randint(0, 50, size=(4, 5))
print(arr2)
print( arr2.itemsize)
print( arr2.nbytes)

[[44 47  0  3  3]
 [39  9 19 21 36]
 [23  6 24 24 12]
 [ 1 38 39 23 46]]
4
80


In [7]:
arr3 = np.arange(1, 13).reshape(3, 4)
print(arr3)
x = arr3[:, ::-1]
print(x)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]
