In [1]:
import numpy as np

In [3]:
arr = np.array([10,20,30,40,50])
print(arr,type(arr))

[10 20 30 40 50] <class 'numpy.ndarray'>


In [5]:
arr_ = np.array([[1,2],[3,4],[5,6]])
print(arr_)

[[1 2]
 [3 4]
 [5 6]]


In [9]:
arr1 = np.array([7,8,9],dtype=float)
print(arr1,type(arr1))

[7. 8. 9.] <class 'numpy.ndarray'>


In [11]:
a = np.zeros(6)
print(a)

[0. 0. 0. 0. 0. 0.]


In [13]:
b= np.ones((3,2),dtype=int)
print(b)

[[1 1]
 [1 1]
 [1 1]]


In [15]:
c=np.empty((2,2))
print(c)
#bcoz due to present of already used values in the memory locations 
#bcoz it will be faster as it skips initialization time 

[[2.12199579e-314 1.13314575e-311]
 [7.66789882e-321 1.13314575e-311]]


In [19]:
d=np.arange(0,20,2)
print(d)

[ 0  2  4  6  8 10 12 14 16 18]


In [23]:
e=np.linspace(0,1,6)
print(e)
#arange function skips the last value (exlusive)
#linspace function keeps the value(inclusive)


[0.  0.2 0.4 0.6 0.8 1. ]


In [25]:
f=np.random.random((3,3))
print(f)

[[0.09350729 0.46966441 0.83243324]
 [0.10583231 0.97536868 0.02257596]
 [0.085236   0.65314839 0.82661119]]
